version: '2'

services:
  app:
    image: 'emotionlogger:latest'
    build:
      context: ../emotion-logger-backend
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/emotiondb
      - SPRING_DATASOURCE_USERNAME=postgresql
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080

  frontend:
    image: 'frontend-image'
    build:
      context: ../emotion-logger-frontend
    container_name: frontend
    restart: always
    ports:
      - '80:80'
    depends_on:
      - app
    command: nginx -g "daemon off;"

  db:
    image: 'postgres:14.0-alpine'
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=emotiondb

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin
    restart: always
    ports:
      - '8000:81'
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgresql@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=81
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
